### PR TITLE
fix: unfreeze objects with non writable properties

### PR DESCRIPTION
**Pull request by dai-shi**
Reported issue: https://github.com/dai-shi/react-tracked/issues/79

I looked at immer source code and didn't find why this happened, but the thing is if object has a non-writable property, this error occurs.
Object is not frozen, so Object.isFrozen() returns false. All we could do is to check all descriptors. 🤷‍♂️

### CODE REVIEW

**Comment by theKashey** [comment]
Can you add a few comments into the code or refer to this issue to make the problem a little more clear for others looking at your code in search of some answers?

By the time few moments are becoming hard to reason and thus tricky.

**Comment by dai-shi** [comment]
Oh, yes, a valid idea.

**Comment by dai-shi** [comment]
This patch didn't solve the issue in react-tracked.

> I looked at immer source code and didn't find why this happened, but the thing is if object has a non-writable property, this error occurs.

There was a huge misunderstanding of mine.
Sadly, the reproduction step in https://github.com/theKashey/proxyequal/issues/25#issue-533616555 doesn't replicate the behavior with immer. (cc @brunolemos )

The reason why it fails with immer is because it freeze objects afterwards. (not because of defineProperty which is not used at all in immer.)

This happens because proxy-compare (and proxyequal too) caches proxies based on object references.
At the first time, we create a proxy from an object that is not frozen, so we don't copy it. And then, immer freezes the object, which leads to the proxy error: `a read-only and non-configurable data property on the proxy target`.

I will create a failing test case and try to solve it in a new PR.

**Comment by peterDijk** [comment]
I was using some outdated versions of both react-tracked and immer in a project i'm working on.
After updating to latest versions I get the same error 
```
Uncaught TypeError: 'get' on proxy: property 'documents' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '#<Object>' but got '[object Object]')
```
What could I do now to fix this?

**Comment by dai-shi** [comment]
@peterDijk I was assuming the latest version of react-tracked fixed fully, but no?? Can you create a repro with codesandbox? If it's reproducible, you want to create a new issue, either on here proxy-compare repo or react-tracked repo, depending on the repro's dependency.

**Comment by peterDijk** [comment]
I will try that later today.
I was on really old versions: react-tracked 1.4.1 and immer 3.1.3
Even updating immer to 4.0.2 (still on same r-tracked) already gives me the proxy error where I'm consuming from the react-tracked state. The reducer is set using immer's `produce`
Using `setAutoFreeze(false)` makes the error go away.
Updated to latest tracked & immer and all still good it seems.

**Comment by dai-shi** [comment]
> Updated to latest tracked & immer and all still good it seems.

You mean the issue is resolved, then?

**Comment by peterDijk** [comment]
by setting `setAutoFreeze(false)` in top-level, yes.
In sandbox without that also no problem, so there is something else wrong in my project.

**Comment by pastelmind** [comment]
I landed here while investigating https://github.com/pmndrs/valtio/issues/749. I'm not too familiar with how Proxy works, so I need help understanding the following comment:

https://github.com/dai-shi/proxy-compare/blob/50868c61461aefd2671503c51c299cd2d74653c3/src/index.ts#L42-L51

Am I correct in assuming that the copy is needed because [the get trap of a Proxy must return the same value as the target's own property if the property is non-configurable *and* non-writable](https://tvcutsem.github.io/frozen-proxies#frozen-proxies)?

**Comment by dai-shi** [comment]
Isn't it what we do now?
https://github.com/pmndrs/valtio/blob/5d0eca7edc25aa7f17fb8082ef14244a35fc12b2/src/vanilla.ts#L128-L130

**Pull request merged**
